apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: app1-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        # Replace with your DockerHub username if following along
        image:dbakhrucpg/app1-backend-container:v1.0.0
        ports:
        - containerPort: 5000