apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-backend-app
  namespace: argocd
spec:
  project: app1-project
  source:
    # This URL corresponds to the backend config repo created in the demo
    repoURL: 'https://github.com/dbakhru433/app1-backend-config.git'
    targetRevision: HEAD
    path: backend
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: app1-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true